rootProject.name = "actiongraph"

include("actiongraph-core")
include("actiongraph-bom")
include("actiongraph-annotations")
include("actiongraph-memory")
include("actiongraph-memory-spring-boot-starter")
include("actiongraph-interpretation")
include("actiongraph-human-review")
include("actiongraph-llm")
include("actiongraph-llm-deepseek")
include("actiongraph-persistence-jdbc")
include("actiongraph-jdbc-spring-boot-starter")
include("actiongraph-spring-boot-starter")
include("actiongraph-governance")
include("actiongraph-governance-spring-boot-starter")
include("actiongraph-console-core")
include("actiongraph-console-jdbc")
include("actiongraph-human-review-spring-boot-starter")
include("actiongraph-console-spring-boot-starter")
include("actiongraph-samples")
