rootProject.name = "actiongraph"

include("actiongraph-core")
include("actiongraph-bom")
include("actiongraph-annotations")
include("actiongraph-component-catalog")
include("actiongraph-control-plane-api")
include("actiongraph-human-review")
include("actiongraph-llm-deepseek")
include("actiongraph-persistence-jdbc")
include("actiongraph-spring-boot-starter")
include("actiongraph-governance")
include("actiongraph-console")
include("actiongraph-console-spring-boot-starter")
include("actiongraph-samples")
