package com.actiongraph.trace;

public enum TraceEventType {
    RUN_STARTED,
    RUN_RESUMED,
    RUN_SUSPENDED,
    PLAN_GENERATED,
    NO_PLAN,
    POLICY_EVALUATED,
    POLICY_DENIED,
    HUMAN_REVIEW_REQUESTED,
    HUMAN_REVIEW_DECIDED,
    RUNTIME_GUARD_FAILED,
    ACTION_STARTED,
    ACTION_SUCCEEDED,
    ACTION_FAILED,
    BLACKBOARD_UPDATED,
    COMPENSATED,
    COMPENSATION_ERROR,
    GOAL_SATISFIED,
    RUN_ENDED
}
