package com.actiongraph.catalog;

import java.util.Arrays;
import java.util.List;

public final class DefaultActionGraphComponentCatalog {
    private DefaultActionGraphComponentCatalog() {
    }

    public static ActionGraphComponentCatalog create() {
        List<ActionGraphComponent> components = list(
                component("actiongraph-bom", ComponentKind.PLATFORM,
                        "Version platform for aligning ActionGraph module versions.",
                        ComponentCompatibility.NO_RUNTIME_CODE,
                        list("version-alignment"), list(), list()),
                component("actiongraph-core", ComponentKind.CORE,
                        "Core GOAP runtime with Action SPI, planner, executor, policy, trace, compensation, and suspend/resume.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("action-spi", "planning", "execution", "policy", "trace", "suspend-resume"),
                        list(), list()),
                component("actiongraph-annotations", ComponentKind.FRAMEWORK,
                        "Pure Java annotation adapter that maps ordinary methods into ActionGraph actions.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("annotation-actions", "reflection-adapter"),
                        list("actiongraph-core"), list("actiongraph-spring-boot-starter")),
                component("actiongraph-memory", ComponentKind.FRAMEWORK,
                        "Structured memory records, repository contracts, and Blackboard context loading.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("structured-memory", "context-loading"),
                        list("actiongraph-core"), list("actiongraph-memory-jdbc", "actiongraph-memory-spring-boot-starter")),
                component("actiongraph-memory-spring-boot-starter", ComponentKind.FRAMEWORK,
                        "Optional Spring Boot defaults for structured memory and JDBC repository auto-configuration.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("spring-memory-autoconfiguration", "spring-jdbc-memory-repository"),
                        list("actiongraph-memory", "actiongraph-memory-jdbc", "actiongraph-jdbc-spring-boot-starter"),
                        list()),
                component("actiongraph-interpretation", ComponentKind.FRAMEWORK,
                        "Goal interpretation contracts, GoalCatalog metadata, clarification results, and Blackboard seeding.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("goal-interpretation", "goal-catalog", "blackboard-seeding"),
                        list("actiongraph-core"), list("actiongraph-llm", "actiongraph-runtime-api")),
                component("actiongraph-runtime-api", ComponentKind.FRAMEWORK,
                        "Reusable non-Spring service for interpret, start, resume, and request metadata tracing entrypoints.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("runtime-entry-service", "interpret-start-resume", "runtime-request-trace-metadata"),
                        list("actiongraph-core", "actiongraph-interpretation"),
                        list("actiongraph-runtime-api-spring-boot-starter")),
                component("actiongraph-human-review", ComponentKind.FRAMEWORK,
                        "Repository-backed human review tasks, approval chains, review policy, callback handling, and task query/decision APIs.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("human-review", "approval-chain", "review-callbacks",
                                "review-task-api-service", "review-decision-service"),
                        list("actiongraph-core"),
                        list("actiongraph-human-review-jdbc", "actiongraph-human-review-api-spring-boot-starter")),
                component("actiongraph-llm", ComponentKind.FRAMEWORK,
                        "Provider-neutral LLM goal interpretation, prompt rendering, and structured output parsing.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("llm-contracts", "prompt-rendering", "structured-output"),
                        list("actiongraph-core", "actiongraph-interpretation"), list("actiongraph-llm-deepseek")),
                component("actiongraph-llm-deepseek", ComponentKind.PROVIDER,
                        "DeepSeek-compatible LLM transport provider.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("deepseek-client"), list("actiongraph-llm"), list()),
                component("actiongraph-persistence-jdbc", ComponentKind.INFRASTRUCTURE,
                        "Low-level JDBC repositories for trace, suspended runs, and trace read models.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("jdbc-trace", "jdbc-suspended-run", "jdbc-trace-read-model"),
                        list("actiongraph-core"), list("actiongraph-jdbc-spring-boot-starter")),
                component("actiongraph-memory-jdbc", ComponentKind.INFRASTRUCTURE,
                        "JDBC structured memory repository.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("jdbc-memory"), list("actiongraph-memory", "actiongraph-persistence-jdbc"),
                        list("actiongraph-memory-spring-boot-starter")),
                component("actiongraph-human-review-jdbc", ComponentKind.INFRASTRUCTURE,
                        "JDBC human-review task repository.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("jdbc-human-review"), list("actiongraph-human-review", "actiongraph-persistence-jdbc"),
                        list("actiongraph-human-review-spring-boot-starter")),
                component("actiongraph-jdbc-spring-boot-starter", ComponentKind.INFRASTRUCTURE,
                        "Optional Spring Boot auto-configuration for durable trace and suspended-run repositories.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("spring-jdbc-runtime-repositories"),
                        list("actiongraph-persistence-jdbc"), list("actiongraph-spring-boot-starter")),
                component("actiongraph-spring-boot-starter", ComponentKind.FRAMEWORK,
                        "Spring Boot runtime starter for annotation scanning and minimal runtime defaults.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("spring-runtime-autoconfiguration", "action-scanning"),
                        list("actiongraph-core", "actiongraph-annotations"), list("actiongraph-jdbc-spring-boot-starter")),
                component("actiongraph-governance", ComponentKind.GOVERNANCE,
                        "Reusable masking, amount-limit, and rule-based permission policies.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("masking", "amount-limits", "permission-policy"), list("actiongraph-core"),
                        list("actiongraph-governance-human-review", "actiongraph-governance-spring-boot-starter")),
                component("actiongraph-governance-human-review", ComponentKind.GOVERNANCE,
                        "Governance extension for review attributes and approval-chain routing.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("review-attributes", "approval-routing"),
                        list("actiongraph-governance", "actiongraph-human-review"),
                        list("actiongraph-governance-human-review-spring-boot-starter")),
                component("actiongraph-governance-spring-boot-starter", ComponentKind.GOVERNANCE,
                        "Optional Spring Boot auto-configuration for masking, amount-limit, and permission policy beans.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("spring-governance-autoconfiguration"),
                        list("actiongraph-governance"), list("actiongraph-spring-boot-starter")),
                component("actiongraph-governance-human-review-spring-boot-starter", ComponentKind.GOVERNANCE,
                        "Optional Spring Boot auto-configuration for review attributes and approval routing.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("spring-review-governance"),
                        list("actiongraph-governance-human-review", "actiongraph-governance-spring-boot-starter"),
                        list("actiongraph-human-review-spring-boot-starter")),
                component("actiongraph-human-review-spring-boot-starter", ComponentKind.FRAMEWORK,
                        "Optional Spring Boot repository-backed human review policy support and JDBC repository auto-configuration.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("spring-human-review-policy", "spring-jdbc-human-review-repository"),
                        list("actiongraph-core", "actiongraph-human-review", "actiongraph-human-review-jdbc",
                                "actiongraph-jdbc-spring-boot-starter"),
                        list()),
                component("actiongraph-console", ComponentKind.CONTROL_PLANE,
                        "Reusable read-only console query service, JDBC read-model adapter, and CSV/JSONL audit export service.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("console-query-service", "console-jdbc-read-model", "audit-export", "csv", "jsonl",
                                "read-only-run-monitoring"),
                        list("actiongraph-core", "actiongraph-persistence-jdbc"),
                        list("actiongraph-console-spring-boot-starter")),
                component("actiongraph-runtime-api-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC runtime interpretation, start, resume, and trace-header capture endpoints.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("runtime-http-api", "runtime-request-trace-metadata"),
                        list("actiongraph-runtime-api", "actiongraph-control-plane-api"),
                        list("actiongraph-component-catalog-spring-boot-starter",
                                "actiongraph-human-review-api-spring-boot-starter",
                                "actiongraph-console-spring-boot-starter")),
                component("actiongraph-human-review-api-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC human-review task query, decision, and callback endpoints.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("human-review-http-api", "human-review-callback-http-api"),
                        list("actiongraph-human-review", "actiongraph-control-plane-api"),
                        list("actiongraph-runtime-api-spring-boot-starter",
                                "actiongraph-component-catalog-spring-boot-starter",
                                "actiongraph-console-spring-boot-starter")),
                component("actiongraph-console-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Spring Boot Console API, UI, export endpoints, shared service auto-configuration, and JDBC read-model repository auto-configuration.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("spring-console-service-autoconfiguration", "console-json-http-api", "console-html-ui",
                                "console-export-http-api", "spring-console-jdbc-repository"),
                        list("actiongraph-console", "actiongraph-control-plane-api"),
                        list("actiongraph-runtime-api-spring-boot-starter",
                                "actiongraph-component-catalog-spring-boot-starter",
                                "actiongraph-human-review-api-spring-boot-starter")),
                component("actiongraph-component-catalog", ComponentKind.CONTROL_PLANE,
                        "Java 8 compatible machine-readable catalog of ActionGraph components and composition profiles.",
                        ComponentCompatibility.JAVA8_CLIENT,
                        list("component-catalog", "composition-profiles"), list(),
                        list("actiongraph-component-catalog-spring-boot-starter")),
                component("actiongraph-control-plane-api", ComponentKind.CONTROL_PLANE,
                        "Java 8 compatible control-plane contracts, properties-based aggregate configuration, safe GET retries, aggregate/runtime/catalog/human-review/console HTTP clients, audit header forwarding, and shared-secret token verification.",
                        ComponentCompatibility.JAVA8_CLIENT,
                        list("control-plane-response-contracts", "error-response-contracts",
                                "java8-control-plane-client", "java8-control-plane-properties",
                                "java8-safe-get-retries", "java8-runtime-client",
                                "java8-component-catalog-client", "java8-human-review-client",
                                "java8-console-client", "http-audit-headers", "shared-secret-token-verification"),
                        list(), list("actiongraph-runtime-api-spring-boot-starter",
                                "actiongraph-component-catalog-spring-boot-starter",
                                "actiongraph-human-review-api-spring-boot-starter",
                                "actiongraph-console-spring-boot-starter")),
                component("actiongraph-component-catalog-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC read-only endpoints for the component catalog.",
                        ComponentCompatibility.JAVA21_PLUS,
                        list("component-catalog-http-api"),
                        list("actiongraph-component-catalog", "actiongraph-control-plane-api"),
                        list("actiongraph-runtime-api-spring-boot-starter",
                                "actiongraph-human-review-api-spring-boot-starter",
                                "actiongraph-console-spring-boot-starter")),
                component("actiongraph-samples", ComponentKind.SAMPLE,
                        "Reference domains, demos, and batch scenarios; not intended as a library dependency.",
                        ComponentCompatibility.SAMPLE_ONLY,
                        list("samples", "demos", "benchmarks"), list(), list())
        );

        List<ActionGraphCompositionProfile> profiles = list(
                profile("core-runtime",
                        "Smallest pure Java runtime kernel.",
                        list("actiongraph-core"),
                        list("Manual action registration and manual persistence wiring.")),
                profile("annotation-runtime",
                        "Pure Java runtime with low-intrusion annotated business methods.",
                        list("actiongraph-core", "actiongraph-annotations"),
                        list("No Spring requirement; business classes do not implement Action.")),
                profile("spring-business-runtime",
                        "Spring Boot business runtime without public control-plane endpoints.",
                        list("actiongraph-spring-boot-starter", "actiongraph-interpretation", "actiongraph-runtime-api"),
                        list("Use this inside business services that expose their own API surface.")),
                profile("durable-spring-runtime",
                        "Spring Boot runtime with durable trace, suspended runs, memory, and review task storage.",
                        list("actiongraph-spring-boot-starter", "actiongraph-jdbc-spring-boot-starter",
                                "actiongraph-memory-spring-boot-starter", "actiongraph-human-review-spring-boot-starter"),
                        list("Requires application DataSource and explicit persistence enablement properties.")),
                profile("runtime-entry-api",
                        "Stable interpret/start/resume service surface without forcing a control-plane bundle.",
                        list("actiongraph-runtime-api", "actiongraph-runtime-api-spring-boot-starter"),
                        list("Spring HTTP endpoint is optional and property-gated.")),
                profile("human-review-control-plane",
                        "Approval task inbox and external decision callback surface.",
                        list("actiongraph-human-review", "actiongraph-human-review-api-spring-boot-starter"),
                        list("Use with JDBC review storage for durable approval inboxes.")),
                profile("console-control-plane",
                        "Read-only operational console and audit export surface.",
                        list("actiongraph-console", "actiongraph-console-spring-boot-starter"),
                        list("The Spring starter exposes API, UI, export endpoints, and optional JDBC read-model repository wiring behind the same actiongraph.console.* gates.")),
                profile("full-control-plane",
                        "Explicit composition for built-in runtime, review, callback, console, catalog, and export endpoints.",
                        list("actiongraph-runtime-api-spring-boot-starter",
                                "actiongraph-component-catalog-spring-boot-starter",
                                "actiongraph-human-review-api-spring-boot-starter",
                                "actiongraph-console-spring-boot-starter"),
                        list("Endpoint beans still require their own enablement properties and backing beans.",
                                "The former aggregate starter has been removed; choose these endpoint starters explicitly.")),
                profile("ecosystem-introspection",
                        "Read-only component catalog for gateways, consoles, and deployment checks.",
                        list("actiongraph-component-catalog", "actiongraph-control-plane-api",
                                "actiongraph-component-catalog-spring-boot-starter"),
                        list("Does not create runtime, persistence, LLM, or business action beans.")),
                profile("control-plane-response-contracts",
                        "Java 8 compatible response DTOs, properties-based aggregate configuration, safe GET retries, aggregate/runtime/catalog/human-review/console HTTP clients, and token verification for endpoint starters and legacy adapters.",
                        list("actiongraph-control-plane-api"),
                        list("Endpoint starters use this module to keep error response JSON consistent.",
                                "Endpoint starters also use this module to keep shared-secret semantics consistent.",
                                "Java 8 applications can use ActionGraphControlPlaneHttpClient to configure all deployed control-plane endpoints from one /actiongraph base URL, or only the split surfaces they enable.",
                                "Java 8 applications can use ActionGraphControlPlaneHttpClientProperties to build the same aggregate client from .properties files, configuration centers, or gateway tables.",
                                "Java 8 applications can opt into GET-only retries for transient catalog, review-task query, and Console read failures without automatically retrying side-effecting POST calls.",
                                "Java 8 applications can use ActionGraphRuntimeHttpClient to call a deployed runtime API without Spring or third-party dependencies.",
                                "Java 8 applications can use ActionGraphComponentCatalogHttpClient to inspect deployed component catalog metadata without Spring or third-party dependencies.",
                                "Java 8 applications can use ActionGraphHumanReviewHttpClient to query and decide deployed human-review tasks without Spring or third-party dependencies.",
                                "Java 8 applications can use ActionGraphConsoleHttpClient to query read-only run status, trace details, and audit exports without Spring or third-party dependencies.")),
                profile("java8-legacy-client",
                        "Java 8 client-side integration for legacy applications and gateways.",
                        list("actiongraph-component-catalog", "actiongraph-control-plane-api"),
                        list("Use actiongraph-component-catalog for local compatibility discovery and composition metadata.",
                                "Use actiongraph-control-plane-api to call deployed ActionGraph runtime, component catalog, human-review, and console endpoints over HTTP through one aggregate client, .properties-based aggregate configuration, safe GET retries, or split endpoint clients.",
                                "Systems that cannot load Java 8 client artifacts should call through HTTP, an enterprise gateway, ESB, or a Java 8+ sidecar instead of embedding ActionGraph jars.",
                                "The embeddable runtime kernel remains java21-plus until a dedicated compatibility refactor removes modern language and library features.")),
                profile("full-pilot-service",
                        "Pilot-oriented composition for a Spring business service with durable runtime, governance, human review, console, and catalog endpoints.",
                        list("actiongraph-spring-boot-starter", "actiongraph-jdbc-spring-boot-starter",
                                "actiongraph-memory-spring-boot-starter", "actiongraph-human-review-spring-boot-starter",
                                "actiongraph-governance-spring-boot-starter",
                                "actiongraph-governance-human-review-spring-boot-starter",
                                "actiongraph-runtime-api-spring-boot-starter",
                                "actiongraph-human-review-api-spring-boot-starter",
                                "actiongraph-console-spring-boot-starter",
                                "actiongraph-control-plane-api",
                                "actiongraph-component-catalog-spring-boot-starter"),
                        list("Endpoint exposure is explicit; include only the endpoint starters the deployment needs."))
        );

        return new ActionGraphComponentCatalog(components, profiles);
    }

    private static ActionGraphComponent component(
            String module,
            ComponentKind kind,
            String description,
            ComponentCompatibility compatibility,
            List<String> capabilities,
            List<String> requires,
            List<String> optionalWith
    ) {
        return new ActionGraphComponent(module, kind, description, capabilities, requires, optionalWith,
                compatibility.label());
    }

    private static ActionGraphCompositionProfile profile(
            String name,
            String description,
            List<String> modules,
            List<String> notes
    ) {
        return new ActionGraphCompositionProfile(name, description, modules, notes);
    }

    @SafeVarargs
    private static <T> List<T> list(T... values) {
        return Arrays.asList(values);
    }
}
