package com.actiongraph.catalog;

import java.util.List;

public final class DefaultActionGraphComponentCatalog {
    private DefaultActionGraphComponentCatalog() {
    }

    public static ActionGraphComponentCatalog create() {
        List<ActionGraphComponent> components = List.of(
                component("actiongraph-bom", ComponentKind.PLATFORM,
                        "Version platform for aligning ActionGraph module versions.",
                        List.of("version-alignment"), List.of(), List.of()),
                component("actiongraph-core", ComponentKind.CORE,
                        "Core GOAP runtime with Action SPI, planner, executor, policy, trace, compensation, and suspend/resume.",
                        List.of("action-spi", "planning", "execution", "policy", "trace", "suspend-resume"),
                        List.of(), List.of()),
                component("actiongraph-annotations", ComponentKind.FRAMEWORK,
                        "Pure Java annotation adapter that maps ordinary methods into ActionGraph actions.",
                        List.of("annotation-actions", "reflection-adapter"),
                        List.of("actiongraph-core"), List.of("actiongraph-spring-boot-starter")),
                component("actiongraph-memory", ComponentKind.FRAMEWORK,
                        "Structured memory records, repository contracts, and Blackboard context loading.",
                        List.of("structured-memory", "context-loading"),
                        List.of("actiongraph-core"), List.of("actiongraph-memory-jdbc", "actiongraph-memory-spring-boot-starter")),
                component("actiongraph-memory-spring-boot-starter", ComponentKind.FRAMEWORK,
                        "Optional Spring Boot defaults for structured memory.",
                        List.of("spring-memory-autoconfiguration"),
                        List.of("actiongraph-memory"), List.of("actiongraph-memory-jdbc-spring-boot-starter")),
                component("actiongraph-interpretation", ComponentKind.FRAMEWORK,
                        "Goal interpretation contracts, GoalCatalog metadata, clarification results, and Blackboard seeding.",
                        List.of("goal-interpretation", "goal-catalog", "blackboard-seeding"),
                        List.of("actiongraph-core"), List.of("actiongraph-llm", "actiongraph-runtime-api")),
                component("actiongraph-runtime-api", ComponentKind.FRAMEWORK,
                        "Reusable non-Spring service for interpret, start, and resume entrypoints.",
                        List.of("runtime-entry-service", "interpret-start-resume"),
                        List.of("actiongraph-core", "actiongraph-interpretation"),
                        List.of("actiongraph-runtime-api-spring-boot-starter")),
                component("actiongraph-human-review", ComponentKind.FRAMEWORK,
                        "Repository-backed human review tasks, approval chains, review policy, and callback handling.",
                        List.of("human-review", "approval-chain", "review-callbacks"),
                        List.of("actiongraph-core"), List.of("actiongraph-human-review-jdbc", "actiongraph-human-review-api")),
                component("actiongraph-human-review-api", ComponentKind.FRAMEWORK,
                        "Reusable non-Spring task query and decision service over a human-review repository.",
                        List.of("review-task-api-service", "review-decision-service"),
                        List.of("actiongraph-human-review"), List.of("actiongraph-human-review-api-spring-boot-starter")),
                component("actiongraph-llm", ComponentKind.FRAMEWORK,
                        "Provider-neutral LLM goal interpretation, prompt rendering, and structured output parsing.",
                        List.of("llm-contracts", "prompt-rendering", "structured-output"),
                        List.of("actiongraph-interpretation"), List.of("actiongraph-llm-deepseek")),
                component("actiongraph-llm-deepseek", ComponentKind.PROVIDER,
                        "DeepSeek-compatible LLM transport provider.",
                        List.of("deepseek-client"), List.of("actiongraph-llm"), List.of()),
                component("actiongraph-persistence-jdbc", ComponentKind.INFRASTRUCTURE,
                        "Low-level JDBC repositories for trace, suspended runs, and trace read models.",
                        List.of("jdbc-trace", "jdbc-suspended-run", "jdbc-trace-read-model"),
                        List.of("actiongraph-core"), List.of("actiongraph-jdbc-spring-boot-starter")),
                component("actiongraph-memory-jdbc", ComponentKind.INFRASTRUCTURE,
                        "JDBC structured memory repository.",
                        List.of("jdbc-memory"), List.of("actiongraph-memory", "actiongraph-persistence-jdbc"),
                        List.of("actiongraph-memory-jdbc-spring-boot-starter")),
                component("actiongraph-human-review-jdbc", ComponentKind.INFRASTRUCTURE,
                        "JDBC human-review task repository.",
                        List.of("jdbc-human-review"), List.of("actiongraph-human-review", "actiongraph-persistence-jdbc"),
                        List.of("actiongraph-human-review-jdbc-spring-boot-starter")),
                component("actiongraph-jdbc-spring-boot-starter", ComponentKind.INFRASTRUCTURE,
                        "Optional Spring Boot auto-configuration for durable trace and suspended-run repositories.",
                        List.of("spring-jdbc-runtime-repositories"),
                        List.of("actiongraph-persistence-jdbc"), List.of("actiongraph-spring-boot-starter")),
                component("actiongraph-memory-jdbc-spring-boot-starter", ComponentKind.INFRASTRUCTURE,
                        "Optional Spring Boot auto-configuration for JDBC memory repositories.",
                        List.of("spring-jdbc-memory-repository"), List.of("actiongraph-memory-jdbc"), List.of()),
                component("actiongraph-human-review-jdbc-spring-boot-starter", ComponentKind.INFRASTRUCTURE,
                        "Optional Spring Boot auto-configuration for JDBC human-review repositories.",
                        List.of("spring-jdbc-human-review-repository"), List.of("actiongraph-human-review-jdbc"), List.of()),
                component("actiongraph-spring-boot-starter", ComponentKind.FRAMEWORK,
                        "Spring Boot runtime starter for annotation scanning and minimal runtime defaults.",
                        List.of("spring-runtime-autoconfiguration", "action-scanning"),
                        List.of("actiongraph-core", "actiongraph-annotations"), List.of("actiongraph-jdbc-spring-boot-starter")),
                component("actiongraph-governance", ComponentKind.GOVERNANCE,
                        "Reusable masking, amount-limit, and rule-based permission policies.",
                        List.of("masking", "amount-limits", "permission-policy"), List.of("actiongraph-core"),
                        List.of("actiongraph-governance-human-review", "actiongraph-governance-spring-boot-starter")),
                component("actiongraph-governance-human-review", ComponentKind.GOVERNANCE,
                        "Governance extension for review attributes and approval-chain routing.",
                        List.of("review-attributes", "approval-routing"),
                        List.of("actiongraph-governance", "actiongraph-human-review"),
                        List.of("actiongraph-governance-human-review-spring-boot-starter")),
                component("actiongraph-governance-spring-boot-starter", ComponentKind.GOVERNANCE,
                        "Optional Spring Boot auto-configuration for masking, amount-limit, and permission policy beans.",
                        List.of("spring-governance-autoconfiguration"),
                        List.of("actiongraph-governance"), List.of("actiongraph-spring-boot-starter")),
                component("actiongraph-governance-human-review-spring-boot-starter", ComponentKind.GOVERNANCE,
                        "Optional Spring Boot auto-configuration for review attributes and approval routing.",
                        List.of("spring-review-governance"),
                        List.of("actiongraph-governance-human-review"), List.of("actiongraph-human-review-spring-boot-starter")),
                component("actiongraph-human-review-spring-boot-starter", ComponentKind.FRAMEWORK,
                        "Optional Spring Boot repository-backed human review policy support.",
                        List.of("spring-human-review-policy"),
                        List.of("actiongraph-human-review"), List.of("actiongraph-human-review-jdbc-spring-boot-starter")),
                component("actiongraph-console-core", ComponentKind.CONTROL_PLANE,
                        "Reusable read-only console query service and response model.",
                        List.of("console-query-service", "read-only-run-monitoring"),
                        List.of("actiongraph-core"), List.of("actiongraph-console-jdbc", "actiongraph-console-api-spring-boot-starter")),
                component("actiongraph-console-jdbc", ComponentKind.CONTROL_PLANE,
                        "JDBC adapter for the console read model.",
                        List.of("console-jdbc-read-model"), List.of("actiongraph-console-core", "actiongraph-persistence-jdbc"),
                        List.of("actiongraph-console-jdbc-spring-boot-starter")),
                component("actiongraph-console-export", ComponentKind.CONTROL_PLANE,
                        "Reusable audit export service for CSV and JSONL run evidence.",
                        List.of("audit-export", "csv", "jsonl"), List.of("actiongraph-console-core"),
                        List.of("actiongraph-console-export-spring-boot-starter")),
                component("actiongraph-console-spring-boot-autoconfigure", ComponentKind.CONTROL_PLANE,
                        "Shared Spring Boot console service auto-configuration without endpoints.",
                        List.of("spring-console-service-autoconfiguration"),
                        List.of("actiongraph-console-core", "actiongraph-control-plane-auth"),
                        List.of("actiongraph-console-api-spring-boot-starter", "actiongraph-console-ui-spring-boot-starter")),
                component("actiongraph-runtime-api-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC runtime interpretation, start, and resume endpoints.",
                        List.of("runtime-http-api"),
                        List.of("actiongraph-runtime-api", "actiongraph-control-plane-api",
                                "actiongraph-control-plane-auth"),
                        List.of("actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-human-review-api-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC human-review task query and decision endpoints.",
                        List.of("human-review-http-api"),
                        List.of("actiongraph-human-review-api", "actiongraph-control-plane-api",
                                "actiongraph-control-plane-auth"),
                        List.of("actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-human-review-callback-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC callback endpoint for external approval systems.",
                        List.of("human-review-callback-http-api"),
                        List.of("actiongraph-human-review", "actiongraph-control-plane-api",
                                "actiongraph-control-plane-auth"),
                        List.of("actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-console-api-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC JSON console endpoints.",
                        List.of("console-json-http-api"),
                        List.of("actiongraph-console-core", "actiongraph-console-spring-boot-autoconfigure",
                                "actiongraph-control-plane-api", "actiongraph-control-plane-auth"),
                        List.of("actiongraph-console-spring-boot-starter", "actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-console-ui-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC built-in console page.",
                        List.of("console-html-ui"),
                        List.of("actiongraph-console-core", "actiongraph-console-spring-boot-autoconfigure"),
                        List.of("actiongraph-console-spring-boot-starter", "actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-console-export-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC CSV/JSONL audit export endpoints.",
                        List.of("console-export-http-api"),
                        List.of("actiongraph-console-export", "actiongraph-console-spring-boot-autoconfigure",
                                "actiongraph-control-plane-api", "actiongraph-control-plane-auth"),
                        List.of("actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-console-jdbc-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring Boot console JDBC repository auto-configuration.",
                        List.of("spring-console-jdbc-repository"), List.of("actiongraph-console-jdbc"), List.of()),
                component("actiongraph-console-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Compatibility aggregate for console API and UI endpoint starters.",
                        List.of("console-api-ui-aggregate"),
                        List.of("actiongraph-console-api-spring-boot-starter", "actiongraph-console-ui-spring-boot-starter"),
                        List.of("actiongraph-console-export-spring-boot-starter")),
                component("actiongraph-control-plane-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Convenience aggregate over runtime, component catalog, human-review, callback, console API, console UI, and export endpoint starters.",
                        List.of("control-plane-aggregate"),
                        List.of("actiongraph-runtime-api-spring-boot-starter",
                                "actiongraph-component-catalog-spring-boot-starter",
                                "actiongraph-human-review-api-spring-boot-starter",
                                "actiongraph-human-review-callback-spring-boot-starter", "actiongraph-console-api-spring-boot-starter",
                                "actiongraph-console-ui-spring-boot-starter", "actiongraph-console-export-spring-boot-starter"),
                        List.of()),
                component("actiongraph-component-catalog", ComponentKind.CONTROL_PLANE,
                        "Reusable machine-readable catalog of ActionGraph components and composition profiles.",
                        List.of("component-catalog", "composition-profiles"), List.of(),
                        List.of("actiongraph-component-catalog-spring-boot-starter")),
                component("actiongraph-control-plane-api", ComponentKind.CONTROL_PLANE,
                        "Java 8 compatible control-plane contracts and lightweight runtime HTTP client.",
                        List.of("control-plane-response-contracts", "error-response-contracts", "java8-runtime-client"),
                        List.of(), List.of("actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-control-plane-auth", ComponentKind.CONTROL_PLANE,
                        "Reusable shared-secret token verification support for control-plane endpoints.",
                        List.of("shared-secret-token-verification", "control-plane-auth"),
                        List.of(), List.of("actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-component-catalog-spring-boot-starter", ComponentKind.CONTROL_PLANE,
                        "Optional Spring MVC read-only endpoints for the component catalog.",
                        List.of("component-catalog-http-api"),
                        List.of("actiongraph-component-catalog", "actiongraph-control-plane-api",
                                "actiongraph-control-plane-auth"),
                        List.of("actiongraph-control-plane-spring-boot-starter")),
                component("actiongraph-samples", ComponentKind.SAMPLE,
                        "Reference domains, demos, and batch scenarios; not intended as a library dependency.",
                        List.of("samples", "demos", "benchmarks"), List.of(), List.of())
        );

        List<ActionGraphCompositionProfile> profiles = List.of(
                profile("core-runtime",
                        "Smallest pure Java runtime kernel.",
                        List.of("actiongraph-core"),
                        List.of("Manual action registration and manual persistence wiring.")),
                profile("annotation-runtime",
                        "Pure Java runtime with low-intrusion annotated business methods.",
                        List.of("actiongraph-core", "actiongraph-annotations"),
                        List.of("No Spring requirement; business classes do not implement Action.")),
                profile("spring-business-runtime",
                        "Spring Boot business runtime without public control-plane endpoints.",
                        List.of("actiongraph-spring-boot-starter", "actiongraph-interpretation", "actiongraph-runtime-api"),
                        List.of("Use this inside business services that expose their own API surface.")),
                profile("durable-spring-runtime",
                        "Spring Boot runtime with durable trace, suspended runs, memory, and review task storage.",
                        List.of("actiongraph-spring-boot-starter", "actiongraph-jdbc-spring-boot-starter",
                                "actiongraph-memory-jdbc-spring-boot-starter", "actiongraph-human-review-jdbc-spring-boot-starter"),
                        List.of("Requires application DataSource and explicit persistence enablement properties.")),
                profile("runtime-entry-api",
                        "Stable interpret/start/resume service surface without forcing a control-plane bundle.",
                        List.of("actiongraph-runtime-api", "actiongraph-runtime-api-spring-boot-starter"),
                        List.of("Spring HTTP endpoint is optional and property-gated.")),
                profile("human-review-control-plane",
                        "Approval task inbox and external decision callback surface.",
                        List.of("actiongraph-human-review", "actiongraph-human-review-api",
                                "actiongraph-human-review-api-spring-boot-starter",
                                "actiongraph-human-review-callback-spring-boot-starter"),
                        List.of("Use with JDBC review storage for durable approval inboxes.")),
                profile("console-control-plane",
                        "Read-only operational console and audit export surface.",
                        List.of("actiongraph-console-core", "actiongraph-console-api-spring-boot-starter",
                                "actiongraph-console-ui-spring-boot-starter",
                                "actiongraph-console-export-spring-boot-starter"),
                        List.of("Add actiongraph-console-jdbc-spring-boot-starter when reading JDBC trace tables.")),
                profile("full-control-plane",
                        "Single-coordinate aggregate for built-in runtime, review, callback, console, and export endpoints.",
                        List.of("actiongraph-control-plane-spring-boot-starter"),
                        List.of("Endpoint beans still require their own enablement properties and backing beans.")),
                profile("ecosystem-introspection",
                        "Read-only component catalog for gateways, consoles, and deployment checks.",
                        List.of("actiongraph-component-catalog", "actiongraph-control-plane-api",
                                "actiongraph-control-plane-auth",
                                "actiongraph-component-catalog-spring-boot-starter"),
                        List.of("Does not create runtime, persistence, LLM, or business action beans.")),
                profile("control-plane-response-contracts",
                        "Java 8 compatible response DTOs and runtime HTTP client for endpoint starters and legacy adapters.",
                        List.of("actiongraph-control-plane-api"),
                        List.of("Endpoint starters use this module to keep error response JSON consistent.",
                                "Java 8 applications can use ActionGraphRuntimeHttpClient to call a deployed runtime API without Spring or third-party dependencies.")),
                profile("control-plane-shared-auth",
                        "Shared token-verification component for Spring MVC endpoint starters.",
                        List.of("actiongraph-control-plane-auth"),
                        List.of("Endpoint starters use this module to keep shared-secret semantics consistent.")),
                profile("full-pilot-service",
                        "Pilot-oriented composition for a Spring business service with durable runtime, governance, human review, console, and catalog endpoints.",
                        List.of("actiongraph-spring-boot-starter", "actiongraph-jdbc-spring-boot-starter",
                                "actiongraph-memory-spring-boot-starter", "actiongraph-memory-jdbc-spring-boot-starter",
                                "actiongraph-human-review-spring-boot-starter",
                                "actiongraph-human-review-jdbc-spring-boot-starter",
                                "actiongraph-governance-spring-boot-starter",
                                "actiongraph-governance-human-review-spring-boot-starter",
                                "actiongraph-control-plane-spring-boot-starter",
                                "actiongraph-control-plane-api",
                                "actiongraph-control-plane-auth",
                                "actiongraph-component-catalog-spring-boot-starter"),
                        List.of("Choose split endpoint starters instead of the aggregate when exposure must be minimized."))
        );

        return new ActionGraphComponentCatalog(components, profiles);
    }

    private static ActionGraphComponent component(
            String module,
            ComponentKind kind,
            String description,
            List<String> capabilities,
            List<String> requires,
            List<String> optionalWith
    ) {
        return new ActionGraphComponent(module, kind, description, capabilities, requires, optionalWith);
    }

    private static ActionGraphCompositionProfile profile(
            String name,
            String description,
            List<String> modules,
            List<String> notes
    ) {
        return new ActionGraphCompositionProfile(name, description, modules, notes);
    }
}
